// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs folder structure. Ordering and
 * category labels are controlled by `sidebar_position` front matter and the
 * `_category_.json` file inside each directory.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
